// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'transaction_dto.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

TransactionDto _$TransactionDtoFromJson(Map<String, dynamic> json) =>
    TransactionDto(
      typeJa: json['Type'] as String,
      typeEn: json['Type_en'] as String,
      tradePrice: json['Trade_Price'] as String,
      pricePerUnit: json['PricePerUnit'] as String?,
      unitPrice: json['UnitPrice'] as String?,
      prefectureCode: json['Prefecture_code'] as String,
      prefecture: json['Prefecture'] as String,
      prefectureEn: json['Prefecture_en'] as String,
      municipalityCode: json['Municipality_code'] as String,
      municipality: json['Municipality'] as String,
      municipalityEn: json['Municipality_en'] as String,
      districtName: json['District_Name'] as String?,
      districtNameEn: json['District_Name_en'] as String?,
      floorPlanJa: json['Floor_Plan'] as String?,
      floorPlanEn: json['Floor_Plan_en'] as String?,
      area: json['Area'] as String,
      landShapeJa: json['LandShape'] as String?,
      landShapeEn: json['LandShape_en'] as String?,
      frontage: json['Frontage'] as String?,
      totalFloorArea: json['TotalFloorArea'] as String?,
      buildingYear: json['Building_Year'] as String?,
      structureJa: json['Structure'] as String?,
      structureEn: json['Structure_en'] as String?,
      useJa: json['Use'] as String,
      useEn: json['Use_en'] as String,
      purposeJa: json['Purpose'] as String?,
      purposeEn: json['Purpose_en'] as String?,
      directionJa: json['Direction'] as String?,
      directionEn: json['Direction_en'] as String?,
      classificationJa: json['Classification'] as String?,
      classificationEn: json['Classification_en'] as String?,
      breadth: json['Breadth'] as String?,
      cityPlanningJa: json['City_Planning'] as String?,
      cityPlanningEn: json['City_Planning_en'] as String?,
      coverageRatio: json['CoverageRatio'] as String?,
      floorAreaRatio: json['FloorAreaRatio'] as String?,
      periodJa: json['Period'] as String,
      periodEn: json['Period_en'] as String,
      renovationJa: json['Renovation'] as String?,
      renovationEn: json['Renovation_en'] as String?,
      remarksJa: json['Remarks'] as String?,
      remarksEn: json['Remarks_en'] as String?,
      latitude: json['Latitude'] as String?,
      longitude: json['Longitude'] as String?,
    );

Map<String, dynamic> _$TransactionDtoToJson(TransactionDto instance) =>
    <String, dynamic>{
      'Type': instance.typeJa,
      'Type_en': instance.typeEn,
      'Trade_Price': instance.tradePrice,
      'PricePerUnit': instance.pricePerUnit,
      'UnitPrice': instance.unitPrice,
      'Prefecture_code': instance.prefectureCode,
      'Prefecture': instance.prefecture,
      'Prefecture_en': instance.prefectureEn,
      'Municipality_code': instance.municipalityCode,
      'Municipality': instance.municipality,
      'Municipality_en': instance.municipalityEn,
      'District_Name': instance.districtName,
      'District_Name_en': instance.districtNameEn,
      'Floor_Plan': instance.floorPlanJa,
      'Floor_Plan_en': instance.floorPlanEn,
      'Area': instance.area,
      'LandShape': instance.landShapeJa,
      'LandShape_en': instance.landShapeEn,
      'Frontage': instance.frontage,
      'TotalFloorArea': instance.totalFloorArea,
      'Building_Year': instance.buildingYear,
      'Structure': instance.structureJa,
      'Structure_en': instance.structureEn,
      'Use': instance.useJa,
      'Use_en': instance.useEn,
      'Purpose': instance.purposeJa,
      'Purpose_en': instance.purposeEn,
      'Direction': instance.directionJa,
      'Direction_en': instance.directionEn,
      'Classification': instance.classificationJa,
      'Classification_en': instance.classificationEn,
      'Breadth': instance.breadth,
      'City_Planning': instance.cityPlanningJa,
      'City_Planning_en': instance.cityPlanningEn,
      'CoverageRatio': instance.coverageRatio,
      'FloorAreaRatio': instance.floorAreaRatio,
      'Period': instance.periodJa,
      'Period_en': instance.periodEn,
      'Renovation': instance.renovationJa,
      'Renovation_en': instance.renovationEn,
      'Remarks': instance.remarksJa,
      'Remarks_en': instance.remarksEn,
      'Latitude': instance.latitude,
      'Longitude': instance.longitude,
    };
